version: '3'
services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=studentportal
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8080:8080

  sp-server:
    image: cdcautomation/student-portal-server:latest
    env_file:
      - .env
    environment:
      DB_HOST: "mysqldb"
    ports:
      - 3001:3001
    depends_on:
      - mysqldb
      - adminer
    command: npm run start:dev