version: '3.1'
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=studentportal
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  sp-client:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: "mysqldb"
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
      - adminer
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    command: npm run start:dev